function zhi = get_modifer(houdu)
%这个是shishi_modifer写成函数形式的。为了方便使用。
%他所谓的厚度修正曲线。讲道理这个是和优化啊什么的高度相关的了。
% Pcp_m = [-0.08 -0.4 ;...
%         -0.06 -0.2 ;...
%         0 0 ;...
%         0.07 0.2;...
%         0.09 0.4;...
%         0.25 1.0 ;...
%         0.5 0.6 ;...
%         0.7 0.13 ;...
%         0.9 0.03 ;...
%         1.0 0 ;...
%         1.1 -0.03 ;...
%         1.3 -0.16 ;...
%         ];
load('thicknessModifyPoint.mat');
zhi  = thkmultip(Pcp_m , houdu) ; 


if(0)
    plot(houdu(:,1),houdu(:,2)) ; 
    hold on ;
    plot(zhi(:,1),zhi(:,2)) ; 
end

end

function zhi = thkmultip(Pcp_m , houdu)
%能写函数还是尽量写函数。混着写可以避免命名的麻烦
[hang lie] = size(houdu) ; 
t = 0:0.1:1 ; 
houdu_m = yangtiao4(Pcp_m , t) ; 
for i = 1:hang 
    houdu(i,2) = houdu(i,2)*(chaxun(houdu_m,(houdu(i,1)))+1) ; 
end
zhi = houdu ; 
end